name: Release Libraries

on:
  workflow_dispatch:
    inputs:
      libs:
        description: 'List of libraries to force new releases for'
        required: true
        type: string
  push:
    branches: [ main ]
    paths:
      - "libs/**.luau"

jobs:
  Main:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
        
    steps:
      - uses: CompeyDev/setup-rokit@v0.1.0
      - uses: actions/checkout@v3

      - name: Run CI
        uses: ./.github/workflows/ci.yml

      - name: Install Toolchain
        run: rokit install --no-trust-check

      - name: Fetch diff
        id: fetch_diff
        shell: bash
        run: |
          echo "diff=$(gh api repos/${{ github.repository }}/commits/${{ github.sha }} --header 'Accept: application/vnd.github.v3.diff')" >> .diff

      - name: Run releases script
        run: lune run scripts/make_lib_releases implprop ${{ inputs.libs }}
